Updated `curlbash` script to simplify the script
Changes:
* Refactored to use a named temporary storage directory.
* Refactored to use a "more compliant" `getopts` parsing
  (Placate shellcheck, avoid using `eval`s).
* Removed redundant options (`-d`, `-r`, `-s`):
  Avoid "simplifying" execution (by passing the burden to the user).
  Focus on doing one job: Download, and Review/Verify (okay, two jobs).
* Use strictly POSIX sh commands.
  * As a consequence, remove `shasum -p -a256` to simplify things
  (as I don't know where `shasum -p -a256` would be pertinent,
   and it complicates the quote-everything axiom).
* Apply shellcheck all over the script.

Bumped version to 0.2.0.

Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

diff --git a/curlbash b/curlbash
--- a/curlbash
+++ b/curlbash
@@ -1,7 +1,8 @@
 #!/bin/sh
 #######################################################################
 # Copyright (c) 2016 Scott Vokes <vokes.s@gmail.com>
-# 
+# Copyright (c) 2024 Stavros Ntentos <133706+stdedos@users.noreply.github.com>
+#
 # Permission to use, copy, modify, and/or distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
 # copyright notice and this permission notice appear in all copies.
@@ -14,168 +15,109 @@
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 #######################################################################
-# Curl a URL, allowing a chance to review/checksum it before executing.
+# Curl a URL and review / verify checksum of its contents.
 #######################################################################
 
-CURLBASH_VERSION="0.1.0"
+CURLBASH_VERSION="0.2.0"
 
 # Defaults
 VERBOSE=0
-CONFIRM=1
-USE_SUDO=0
 EXPECTED_SHA256=0
-FETCH_AND_EXIT=0
 USE_CACHE=1
-DELETE_AFTER_EXEC=1
-PAGER=${PAGER:-less}
-SUDO=${SUDO:-sudo}
+TMP_STORE_DIR="${TMP_STORE_DIR:-${TMPDIR:-/tmp}/$(basename "$0")}"
+
+mkdir -p "${TMP_STORE_DIR}"
+# shellcheck disable=SC2064 # Intentional immediate expansion
+trap "rmdir '${TMP_STORE_DIR}' 2>/dev/null" EXIT INT TERM HUP QUIT ABRT
 
 usage() {
-    echo "curlbash version ${CURLBASH_VERSION} by Scott Vokes"
-    echo "Usage: curlbash [-c] [-d] [-e SHA256] [-f | -r] [-h] [-v] URL"
-    echo "  -c           ignore cache"
-    echo "  -d           don't delete cached downloads"
-    echo "  -e SHA256    expect this SHA256, or exit"
-    echo "  -f           fetch and exit"
-    echo "  -h           print this help and exit"
-    echo "  -r           run, without confirmation"
-    #echo "  -s           run with sudo"
-    echo "  -v           increase verbosity"
+    >&2 echo "curlbash version ${CURLBASH_VERSION} by Stavros Ntentos"
+    >&2 echo
+    >&2 echo "Usage: curlbash [-c] [-e SHA256] [-h] [-v] URL"
+    >&2 echo "  -c           ignore cache"
+    >&2 echo "  -e SHA256    expect this SHA256, or exit"
+    >&2 echo "  -h           print this help and exit"
+    >&2 echo "  -v           increase verbosity"
 }
 
-log() {
-    if [ $VERBOSE -gt 0 ]; then
-        echo "###" $*
+debug() {
+    if [ "${VERBOSE}" -gt 0 ]; then
+        echo "### $1"
     fi
 }
 
-fetch() {
-    log "Saving $URL to $CACHE_FILE"
-    curl --fail --silent --show-error --location "$1" -o "$2" || exit
-    chmod u+x "$2"
+die() {
+  # Complain to STDERR and exit with error.
+  >&2 echo "$*"
+  exit 2;
 }
 
-run() {
-    log "Running $1"
-    if [ $USE_SUDO -gt 0 ]; then
-        $SUDO "$1"
-    else
-        "$1"
-    fi 
-}
-
-cleanup() {
-    if [ $DELETE_AFTER_EXEC -gt 0 ]; then
-        log "Deleting $1"
-        rm "$1"
-    else
-        log "Skipping deletion"
-    fi
+needs_arg() {
+  if [ -z "{$OPTARG}" ]; then
+    die "No argument provided for the -${OPT} option"
+  fi
 }
 
 parse_args() {
-    args=`getopt cde:fhrsv $*`
-    if [ $? != 0 ]; then
-        usage
-        exit 1
-    fi
-
-    set -- $args
-    for i
-    do
-        case "$i"
-        in
-            -c)                 # ignore cache
-                USE_CACHE=0
-                shift;;
-            -d)                 # don't delete download
-                DELETE_AFTER_EXEC=0
-                shift;;
-            -e)                 # compare hash
-                EXPECTED_SHA256="$2"
-                shift
-                shift;;
-            -f)                 # fetch only
-                FETCH_AND_EXIT=1
-                shift;;
-            -h)                 # print help
-                usage
-                exit 0;;
-            -r)                 # just run
-                CONFIRM=0
-                shift;;
-            -s)
-                USE_SUDO=1
-                shift;;
-            -v)                 # verbose
-                VERBOSE=1
-                shift;;
-            --)
-                shift; break;;
-        esac
+    while getopts ce:fhv OPT; do
+      case "$OPT" in
+        c) USE_CACHE=0;;
+        e) needs_arg; EXPECTED_SHA256="$OPTARG" ;;
+        h) usage; exit 0;;
+        v) VERBOSE=1;;
+        \? ) exit 2 ;;                     # bad short option (error reported via getopts)
+        * ) die "Illegal option --$OPT" ;; # bad long option
+      esac
     done
+    shift $((OPTIND-1))
+
     URL="$1"
 }
 
 exists_in_path() {
-    type $1 >/dev/null 2>/dev/null
+    command -V "$1" >/dev/null 2>/dev/null
 }
 
 # Try to find program to SHA256
 if exists_in_path "sha256"; then
     SHA256="sha256"
-elif exists_in_path "shasum"; then
-    SHA256="shasum -p -a256 "
+elif exists_in_path "sha256sum"; then
+    SHA256="sha256sum"
 else
-    echo "Error: Could not find a program for SHA256 checksums."
-    echo "    Install shasum or sha256 and add it to your path."
+    echo "Error: Could not find sha256/sha256sum for SHA256 checksums on PATH!" >&2
+    exit 1
 fi
 
-parse_args $*
+parse_args "$@"
 
-if [ -z $URL ]; then
+if [ -z "${URL}" ]; then
     usage
     exit 1
 fi
 
-HASH=$(echo -n $URL | ${SHA256} | awk '{print($1)}')
-CACHE_FILE=${TMP:-/tmp}/$HASH
+HASH="$(echo "${URL}" | "${SHA256}" | awk '{print($1)}')"
+CACHE_FILE="${TMP_STORE_DIR}/${HASH}"
 
-if [ -e $CACHE_FILE ] && [ $USE_CACHE = 1 ]; then
-    log "Using existing cache at $CACHE_FILE"
+if [ -s "${CACHE_FILE}" ] && [ "${USE_CACHE}" = 1 ]; then
+    debug "Using existing cache at ${CACHE_FILE}"
 else
-    fetch "$URL" "$CACHE_FILE"
+    echo "Saving ${URL} to ${CACHE_FILE}"
+    curl --fail --silent --show-error --location "${URL}" > "${CACHE_FILE}" || exit $?
+    chmod u+x "${CACHE_FILE}"
 fi
 
-if [ $FETCH_AND_EXIT = 1 ]; then
-    exit 0
-fi
-   
-if [ $EXPECTED_SHA256 != 0 ]; then
-    log "Comparing checksums, expecting $EXPECTED_SHA256"
-    CHECKSUM=$(${SHA256} "$CACHE_FILE" | awk '{print($1)}')
-    log "Got checksum $CHECKSUM"
-    if [ $EXPECTED_SHA256 != $CHECKSUM ]; then
-        echo ""
+SHA256_OUTPUT=$("${SHA256}" "$CACHE_FILE")
+echo "${SHA256_OUTPUT}"
+if [ "${EXPECTED_SHA256}" != 0 ]; then
+    CHECKSUM="$(echo "${SHA256_OUTPUT}" | awk '{print($1)}')"
+    printf "Comparing checksums, expecting %s" "${EXPECTED_SHA256}"
+    if [ "${EXPECTED_SHA256}" != "${CHECKSUM}" ]; then
+        echo
         echo "### WARNING: Checksum mismatch!"
-        echo "### EXP: $EXPECTED_SHA256"
-        echo "### GOT: $CHECKSUM"
+        echo "### EXP: ${EXPECTED_SHA256}"
+        echo "### GOT: ${CHECKSUM}"
         exit 1
-    fi
-fi
-
-if [ $CONFIRM = 1 ]; then
-    $PAGER "${CACHE_FILE}"
-    printf "Continue? [y/N] "
-    read CONTINUE
-
-    if [ ${CONTINUE:-n} = "y" ]; then
-        run "${CACHE_FILE}"
-        cleanup "${CACHE_FILE}"
     else
-        log Exiting.
-        exit 0
+        echo ": OK"
     fi
-else
-    run "${CACHE_FILE}" && cleanup "${CACHE_FILE}"
 fi
